name: Bug Report
description: File a bug report
labels: [ "triage" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug 🐱!

        Please check existing open/closed issues before submitting a new one. Someone might have already encountered a similar problem 😉!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the issue.
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: Link to the page
      description: The link to the page where the issue occurs.
      placeholder: https://exploreme.pro
  
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        Explain how to reproduce the issue in the development environment.

  - type: input
    id: backend-version
    attributes:
      label: Backend version
      description: The release version of the backend or branch/commit.
      placeholder: v4.0.0
    validations:
      required: true

  - type: input
    id: frontend-version
    attributes:
      label: Frontend version
      description: The release version of the frontend or branch/commit.
      placeholder: v4.2.1

  - type: input
    id: os-version
    attributes:
      label: Operating system
      description: The operating system this issue occurred with.
      placeholder: Linux/macOS/Windows

  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: |
        Use this section to provide any additional information you might have (e.g screenshots or screencasts).